### ISSUE TITLE
props값 전달 이슈

### ISSUE THREAD

**Issue by Kayaleeeee** [Kayaleeeee/What_should_I_eat#2]
Naver map에서 kakaomap으로 전환하면서 <KakaoMap>컴포넌트를 새로 만들었습니당.
기존에 Map.js에 다 때려넣었던 것을 KakaoMap으로 빼면서, 지현씨가 설정한 lat이랑 long을 KakaoMap컴포넌트로
넘겨주고 싶어요....

  <KakaoMap latitude={latitude} longitude={longitude} test={"test"} />
로 전달해주면 test 스트링 값만 넘어오고 나머지는 다 undefined입니다.
흑흑흑 도와주세요

**Comment by 7hong13** [comment]
스펠링 에러(longitude <-> longtitude) 때문에 생긴 문제라서, 고치고 해결했습니다~!
